# Generated by network generator
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
from keras.layers import Conv1D
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import BatchNormalization
from keras.layers.merge import concatenate

layer_000 = Input(shape=(28,28))
layer_001 = Conv1D(9, 3, activation='sigmoid')(layer_000)
layer_002 = Conv1D(2, 3, activation='tanh')(layer_001)
layer_004 = Conv1D(6, 3, activation='tanh')(layer_002)
layer_048 = BatchNormalization()(layer_004)
mnist_block01 = Flatten()(layer_048)
mnist_block02 = Dense(544, activation="relu")(mnist_block01)
mnist_block03 = Dropout(0.43968582)(mnist_block02)
layer_049 = Dense(544, activation="softmax")(mnist_block03) # this is the last layer of mnist block
layer_last = Dense(10, activation='sigmoid')(layer_049)
model = Model(inputs=layer_000, outputs=layer_last)